facebook/flow

lib/node.js
First pull request. Began implementing missing node.js http module.
=> Partial implementation of HTTP module

src/commands/commandUtils.ml, src/parser/README.md, src/parser/package.json
=> Fix typo: Javascript to JavaScript

docs/02-running.md
Older versions of the JSXTransformer don't seem to work with flow. I edited the doc to suggest using the latest (0.12.2)
=> Added suggested version of JSXTransformer

lib/core.js
Fixes #240 
I used http://dev.w3.org/html5/webstorage/#storage-0 as a reference.
=> Fix types for sessionStorage and Storage

lib/react.js
[Specified here](http://facebook.github.io/react/docs/events.html#syntheticevent)
=> Add SyntheticEvent to lib/react.js

src/commands/statusCommands.ml
=> flow status --json should exit 2 on errors

lib/react.js
c.f. http://facebook.github.io/react/docs/events.html and react/lib/Synthetic*Event.js
=> Types for React synthetic events

lib/core.js
=> Declare prompt function (fixes #204)

lib/react.js
As per http://facebook.github.io/react/blog/2015/03/03/react-v0.13-rc2.html#react.cloneelement
=> Support for React.cloneElement in 0.13

static/flow.css
300 was really hard to read, especially combined with `-webkit-font-smoothing: antialiased`
=> Increase base font-weight

lib/node.js
Added missing Node.js http.get() implementation
=> node http.get() implementation

src/typing/type_inference_js.ml, tests/react/proptype_oneOfType.js, tests/react/react.exp
My original changes got reverted in an upstream sync commit.
=> Re-add merged out oneOfType proptype implementation

lib/node.js
Partial fs module implementation
=> Partial fs module implementation

README.md
Added section to README to explain how to run tests.
=> Document testing

.gitignore
these are created during `npm test`
=> Add some build/test artifacts to .gitignore

lib/node.js
Other fs methods implementation for my lovely tool.
=> More fs implementation

lib/node.js
- add setImmediate function declaration
- add clearImmediate function declaration
=> Add "Immediate" global timer funcs to Node lib

src/typing/autocomplete_js.ml, src/typing/constraint_js.ml, src/typing/constraint_js.mli, src/typing/env_js.ml, src/typing/env_js.mli, src/typing/flow_js.ml, src/typing/flow_js.mli, src/typing/type_inference_js.ml
Small rename changes from #404 that will make that long-lived branch easier to merge down the road. @jeffmo
=> Rename block to scope

lib/node.js
=> Add defs for Node's 'os' module

README.md
=> spell out build deps for debian/Ubuntu

docs/01-declarations.md, docs/04-cli.md
"_Declarations_" and "_Using the CLI_" sections were modified.
=> Fixed some typos in documentation

docs/01-dynamic-type-tests.md, docs/01-nullable-types.md
* code examples galore
* where type tests can be used
* (very nearly) exhaustive list of supported tests
* caveat section about havocked refinements
=> Improve docs for dynamic type tests

docs/01-dynamic-type-tests.md
=> Fix broken link

docs/02-underscore.md
=> Remove watch-out-here-comes-an-s apostrophe from documentation

_data/authors.yml, _posts/2015-11-09-Generators.md
=> Add blog post describing typed generators

_includes/footer.html
=> Update year to 2016 in footer layout

README.md
Inverted order of brew commands in Install section. For all the people like me who will always do:
```
brew install flow
brew update
brew install flow
```
=> small edit in docs

hack/.ocamlformat
The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.
=> Re-sync with internal repository

hack/utils/core/exception.ml, hack/utils/core/exception.mli, hack/utils/core/hh_logger.ml, hack/utils/core/hh_logger.mli, hack/watchman/watchman.ml, hack/watchman/watchman_lwt.ml, hack/watchman/watchman_sig.ml
fbshipit-source-id: 0dd75570b90446b274b641c1f4e8e61cd73d8077
=> Sync hack changes
