src/typing/flow_js.ml
tests/misc/F.js
tests/misc/G.js
tests/misc/misc.exp

Enable type checker to correctly type non-standard length properties.
Fixes issue #131.

Removed hard-coded .length case

---

lib/dom.js

According to https://developer.mozilla.org/en-US/docs/Web/API/Blob.Blob type and endings are optional arguments.
(http://dev.w3.org/2006/webapi/FileAPI/#dfn-BlobPropertyBag also says type is optional, but has no endings argument at all)

Resubmit #113 this fixes #155

---

lib/dom.js
tests/union/union.exp

Adds a declaration for the document's [`execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/document.execCommand), copied from the already-implemented IE-only textRange's `execCommand()`.

Add declaration for Document.execCommand()

---

src/common/errors_js.ml

Fixes #220
I didn't add a command line flag since hack uses `--color` for a very different meaning, and `--no-color` would be confusing if we ever add hack's `--color`.

disable colors when TERM=dumb

---

docs/02-running.md

Other tools (like Babel) are available and can solve problems devs have with the react-tools transform. I wanted to make devs aware of them, and one way to do this is via the wiki. If such a list should instead be included into the site, that's fine for me as well.

Include information about third party tools

---

src/typing/type_inference_js.ml
tests/react/jsx_spread.js
tests/react/proptype_oneOf.js
tests/react/react.exp

I noticed when digging around the source that a number of PropTypes are not supported, and thought this would be a good place to start contributing.
I tried to follow the style of the existing code, but I would appreciate any formatting critiques.
I'm not super happy with the way I'm creating the string literal EnumT, as I copied it from `convert`. Should this code be factored out into a utility, or is there a better way to go about this?
Hope this helps!

Add one of proptype

---

src/typing/flow_js.ml
src/typing/type_inference_js.ml
tests/new_react/new_react.exp
tests/react/proptype_arrayOf.js
tests/react/proptype_func.js
tests/react/proptype_object.js
tests/react/proptype_objectOf.js
tests/react/react.exp

Implemented `func`, `object`, and `objectOf`. Added tests for the existing `arrayOf` proptype. "Fixed" issue flowing React props to generated proptypes (see  ba95d17).

Implement more PropTypes

---

src/typing/type_inference_js.ml
tests/react/proptype_oneOfType.js
tests/react/react.exp

Each expression in the array becomes a type in a union. It's possible (likely even) that we will produce a union containing an AnyT, but I don't believe that will be a problem. If the array is empty, we will create an "empty union" which should not admit any value. If the array contains a spread, we fall back to AnyT.

Implement PropTypes.oneOfType

---

lib/node.js

_I'm just experimenting with Flow - so if this PR sucks, it's ok to just say so_
Things I'm not totally clear on:
* The `path` module exports `posix` and `win32` - they have the same interface as `path`. How do I express that? See https://github.com/joyent/node/blob/a995a6a/lib/path.js#L620-L626
* `querystring` has undocumented aliases for `stringify` and `parse` (`encode` and `decode` respectively). Should they be included?
* `url#parse` can return a `query` that can be `null | string | Object`, but I couldn't get that to work in any form.

Add type signature for node "url", "querystring" and "path" modules

---

lib/dom.js

Resolve #173 by adding missing HTMLImageElement properties including `complete`. This adds all properties defined at https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element.
This is my first PR, would appreciate feedback of anything I'm missing or doing wrong :-)

Add missing HTMLImageElement properties

---

src/typing/env_js.ml
src/typing/env_js.mli

useful for printing `Env_js.env` for debugging.
prints each block like an object, e.g.
```
{
foo: ...;
.this: ...;
.exports: ...;
}
```

Env printer

---

src/typing/type_inference_js.ml
tests/refinements/refinements.exp
tests/refinements/switch.js

Refines switch statements as if they were `===` binary expressions with the discriminant on the LHS and the case expression on the RHS.
This is similar to the handling for if/else if/else, except complicated by fallthroughs. `fallthrough_ctx` is a clone of the `ctx` from before the switch, which has been refined by the //not// of all of the case statements seen so far. `last_ctx` is similar, but it assumes the previous cases can all be true -- except that each time a `break` or `return` happens, `last_ctx` gets emptied out. merging `fallthrough_ctx` with `last_ctx` gives you `case_ctx`, which is correct for just that case statement.
For example:
```
function x(foo: string | number | boolean) {
switch (typeof foo) {
case 'string':
// fallthrough_ctx: string | number | boolean
// case_ctx: …
```

Refine switch cases

---

src/parser/Makefile
src/parser/package.json

As suggested on #387, use `make` to move around the `README`'s. This works
great :)

Publish flow-parser 0.4.0 and add make rule to npm publish

---

Makefile

Make a bytecode version of `flow` for use by `ocamldebug`.  This `flow` build allows devs to step through Flow with `flow single`.

Facilitate debug builds

---

src/typing/flow_js.ml
src/typing/type_inference_js.ml
tests/cycle/cycle.exp
tests/destructuring/destructuring.exp
tests/error_messages/error_messages.exp
tests/es6modules/es6modules.exp
tests/es6modules/es6modules.js
tests/import_type/import_type.exp
tests/requireLazy/requireLazy.exp
tests/type_only_vars/type_only_vars.exp

This improves error message clarity for ES6 module imports and also general property/global variables when the name being looked up is not found.
Rather than "unknown global variable", now we say "Could not resolve name: %s".
Rather than "Required module not found", now we say "Required module not found: %s".
ES6 module errors are also more fine-grained now (rather than just using a summary of the import string syntax as the reason for pretty much everything).
See updated tests for example output

Improve error message clarity in a few places

---

src/typing/type_inference_js.ml
tests/react/import_react.js
tests/react/react.exp

With a normal CommonJS module, when the exports object is assigned we mark it as a CommonJS default export. This lets the flow system understand that it needs to be mapped properly to an ES6 ModuleNamespace object when imported from an ES6 module.
Declared modules, however, weren't treating their exports in this way as well. This fixes the issue by marking declared module exports as CJSDefault.
More tangibly, this PR fixes this issue: https://github.com/facebook/flow/issues/400

Make interface-defined modules work with CommonJS/ES6Module interop

---

lib/node.js

The types added in this commit were designed based on the definitions of
the relevant functions [here](https://nodejs.org/api/child_process.html#child_process_synchronous_process_creation)
An attempt was made to follow the conventions found in lib/node.js, but
there wasn't a precedent for return objects hence the name spawnRet.

Add types for execSync, execFileSync, spawnSync

---

docs/00-getting-started.md

when last line of .bashrc file is a comment, follow command add path end of comment, so it becomes a comment.
```bash
$> echo "PATH=\"\$PATH:$(pwd)/\"" >> ~/.bashrc && source ~/.bashrc
```
for avoid this situation I add a break line before path
```bash
$> echo -e "\nPATH=\"\$PATH:$(pwd)/\"" >> ~/.bashrc && source ~/.bashrc
```

Update echo PATH command

---

lib/core.js
src/parser/package.json
tests/async/async.exp
tests/date/date.exp
tests/date/date.js
tests/forof/forof.exp
tests/include/include.exp
tests/iterable/iterable.exp
tests/lib/lib.exp
tests/object_api/object_api.exp
tests/promises/promises.exp
tests/union/union.exp

Pull request #537, now with fixed tests (changed line numbers in core.js).
Partially solves #188
Includes updated test case.
It looks like overloaded constructors are not supported, so this doesn't detect all invalid constructor calls (see examples in the test case).

Date constructor definition (fixed tests)

---

src/typing/flow_js.ml
tests/optional/optional_param3.js

There is already a flow for `VoidT ~> OptionalT`, but in the case of
function parameters, `multiflow` actually unwraps the `OptionalT`, so by
the argument flows into the parameter, flow isn't able to detect this
case.
I fixed this by adding a redundant case to `multiflow` instead of a
larger overhaul that would use the existing flow.
Note that functions with default argument values use the same mechanism
as optional parameters. The included test ensures that the default
expression type still flows correctly.
Fixes #437

Allow `undefined` to be passed to optional params

---

.travis-ci.sh
.travis.yml

This is pretty easy, just need to do apt-install-y things using the config
rather than manually.
The OSX build doesn't seem to use containers yet, but the Linux one does. The OSX build also seems to ignore the apt addon, which is good :)
Fixes #626

Update travis config to use containers

---

docs/02-advanced-configuration.md

Attempting to write a `.flowconfig` based on existing docs will give an
"Unable to parse line" error. The updated docs reflect the formatting permitted
by `flowConfig.ml:384`

Update "Advanced configuration" docs

---

.merlin

Now, you will not have merlin saying there is 274 errors because of no `.merlin` :D !

Adds merlin file configuration

---

_posts/2015-10-07-Version-0.17.0.md

This makes it so that users can see this specific release's change, and releases are unlikely to change after getting tagged.

Link to release tag instead of changelog

---

docs/01-arrays.md

The existing docs reference an 8 element limit, which AFAICT is no
longer accurate. I also removed some language referring to an earlier
type declaration which a) I couldn't actually find and b) didn't seem to
explain very much.
Closes #924

Clarify tuple documentation

---

docs/01-union-intersection-types.md

"Parenthesis are important" sounds really silly.

Pluralize "parenthesis"

---

docs/02-running.md
static/transformer.js

The live coding example at http://flowtype.org/docs/running.html is broken due to the linked react version having been bumped to 0.14
Unfortunately I am unable to install the missing jekyll dependencies on my ubuntu machine (I gave up after an hour), so I could only test this fix by manually converting the markdown into HTML. If it needs changes to work in the jekyll env let me know.
On a side note, the page is also 404ing on `showdown.js` but I did not want to pull it in from some CDN as I don't know about your policies regarding this.

fix live example in 02-running

---

.travis-ci.sh
.travis.yml

- Only run 4 tests in parallel on linux containers
- Use the right versions of ocaml on linux containers
- Use travis folds in the log output

Some Travis CI fixes

---

docs/00-getting-started.md

This updates the flow-bin location to the repo in the "flowtype" org, since it already redirects there anyway (it could arguably point to the npm page instead).
Also, npm cases its own name as "npm". Also sentence-cased the heading like the others.

Update flow-bin link and use "npm" casing

---

docs/02-underscore.md

"is can be called" -> "callable"
Not worth signing a CLA for. Maybe someone else can do a quick fix here.

docs - minor wording

---

.gitattributes

I noticed a fresh clone of the Flow repo on Windows led to `website/docs/flow-state.gif` appearing changed. The fix is to add `.gif` files to the `.gitattributes` file, so that the `eol=lf` stuff doesn't mess with them

Add gif to .gitattributes

---

hack/common/common.ml

The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.

Re-sync with internal repository
